
export const ASTEROID_DATA = "ASTEROID_DATA";
export const SET_ASTEROID_DATA = "SET_ASTEROID_DATA";
export const ASTEROID_RANDOM = "ASTEROID_RANDOM";
export const SET_ASTEROID_RANDOMDATA = "SET_ASTEROID_RANDOMDATA";